# Workflow name that will appear in the GitHub "Actions" section
name: Build and Release Executables

# Trigger: when to start the workflow
on:
  push:
    tags:
      - 'v*' # Triggers every time you create and publish a tag starting with "v" (e.g., v3.1, v3.1.1, etc.)

# Jobs to run
jobs:
  build:
    # Job name, which will be dynamic based on the operating system
    name: Build on ${{ matrix.os }}
    # Operating system to run the job on (Windows and macOS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    # Steps that make up the job
    steps:
      # 1. Checkout the repository code onto the virtual machine
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the specified Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # We use Python 3.10, compatible with your libraries

      # 3. Install all project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install requirements from file
          pip install -r requirements.txt
          # Install pyinstaller and other common problematic dependencies for ultralytics
          pip install pyinstaller pandas seaborn

      # 4. Run PyInstaller to create the executable
      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "SpeedAnalyzer" \
          --add-data "yolo:yolo" \
          --hidden-import "pandas" \
          --hidden-import "seaborn" \
          --hidden-import "ultralytics.utils" \
          --hidden-import "pkg_resources.extern" \
          GUI.py

      # 5. Upload the result (the executable) as an "artifact"
      # This allows you to download the files at the end of the process
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # The artifact name will be "SpeedAnalyzer-windows-latest" or "SpeedAnalyzer-macos-latest"
          name: SpeedAnalyzer-${{ matrix.os }}
          # The folder to upload, which contains the compiled file
          path: dist/
