# Workflow name that will appear in the GitHub "Actions" section
name: Build and Release Executables

# Trigger: when to start the workflow
on:
  push:
    tags:
      - 'v*' # Triggers every time you create and publish a tag starting with "v"

# Jobs to run
jobs:
  build:
    # Job name, which will be dynamic based on the operating system
    name: Build on ${{ matrix.os }}
    # Operating system to run the job on (Windows and macOS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            asset_name: SpeedAnalyzer-windows.zip
          - os: macos-latest
            asset_name: SpeedAnalyzer-macos.zip

    # Steps that make up the job
    steps:
      # 1. Checkout the repository code onto the virtual machine
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the specified Python version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install all project dependencies from the requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run PyInstaller to create the executable
      - name: Build with PyInstaller
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            PYINSTALLER_FLAGS="--onefile"
          else
            PYINSTALLER_FLAGS="--onedir"
          fi
          pyinstaller --noconfirm $PYINSTALLER_FLAGS --windowed --name "SpeedAnalyzer" GUI.py

      # 5. Package the executable into a .zip file for the release
      - name: Package the executable
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            # On Windows, the executable is dist/SpeedAnalyzer.exe
            7z a ${{ matrix.asset_name }} ./dist/SpeedAnalyzer.exe
          else
            # On macOS, the executable is a .app folder in dist/
            cd dist
            zip -r ../${{ matrix.asset_name }} ./SpeedAnalyzer.app
            cd ..
          fi

      # 6. Upload the packaged executable as an artifact for the next job
      - name: Upload packaged executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}

  # This job creates the release
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Download all artifacts (the .zip files) created by the build job
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # 2. Use a specialized action to create the release and upload the files
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # This action automatically uses the annotated tag's message as the release body
          files: artifacts/**/*.zip